logging:
    file:
        name: sboard
    level:
        jdbc:
            connection: info
            resultsettalbe: info
            sqlonly: info
            sqltiming: info
        root: info

mybatis:
    mapper-locations: classpath:mappers/**/*.xml

server:
    port: 8080
    servlet:
        context-path: /sboard

spring:
    application:
        name: sboard

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        password: 123$qweR
        url: jdbc:mysql://127.0.0.1:3306/jboard
        username: hyeji
    devtools:
        restart:
            enabled: false

    # 이메일 설정
    mail:
        host: smtp.gmail.com
        port: 587
        username: hyeji111544@gmail.com
        password: tlme osvq zpvx wvkl
        properties:
            mail:
                smtp:
                    auth: true
                    timeout: 5000
                    starttls:
                        enable: true
    jpa:
        database: mysql
        hibernate:
            # 배포할 떄는 none, 개발할 때는 update
            ddl-auto: update
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        properties:
            hibernate:
                format_sql: true
                show_sql: true
    # 파일 업로드 설정
    servlet:
        multipart:
            location: uploads/
            max-file-size: 10MB

# 파일 경로 설정
file:
    upload:
        path: uploads/





